# Generated by Django 3.2.13 on 2023-12-31 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerRepository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RowNumber', models.CharField(max_length=100)),
                ('CustomerId', models.CharField(max_length=100)),
                ('Surname', models.CharField(max_length=100)),
                ('CreditScore', models.CharField(max_length=100)),
                ('Geography', models.CharField(max_length=100)),
                ('Gender', models.CharField(max_length=100)),
                ('Age', models.CharField(max_length=100)),
                ('Tenure', models.CharField(max_length=100)),
                ('Balance', models.CharField(max_length=100)),
                ('NumOfProducts', models.CharField(max_length=100)),
                ('HasCrCard', models.CharField(max_length=100)),
                ('IsActiveMember', models.CharField(max_length=100)),
                ('EstimatedSalary', models.CharField(max_length=100)),
                ('Exited', models.CharField(max_length=100)),
                ('Complain', models.CharField(max_length=100)),
                ('SatisfactionScore', models.CharField(max_length=100)),
                ('CardType', models.CharField(max_length=100)),
                ('PointEarned', models.CharField(max_length=100)),
                ('Mobile', models.CharField(max_length=100)),
                ('CardNo', models.CharField(max_length=100)),
            ],
        ),
    ]
