# Generated by Django 3.2.13 on 2023-12-31 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_customerrepository'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerrepository',
            name='DOB',
            field=models.DateField(blank=True, null=True),
        ),
    ]
