# Generated by Django 3.2.13 on 2023-12-31 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0004_auto_20231231_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerrepository',
            name='Age',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customerrepository',
            name='Balance',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customerrepository',
            name='CardNo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customerrepository',
            name='CardType',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customerrepository',
            name='Complain',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customerrepository',
            name='CreditScore',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customerrepository',
            name='CustomerId',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customerrepository',
            name='DOB',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerrepository',
            name='EstimatedSalary',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customerrepository',
            name='Exited',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customerrepository',
            name='Gender',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customerrepository',
            name='Geography',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customerrepository',
            name='HasCrCard',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customerrepository',
            name='IsActiveMember',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customerrepository',
            name='Mobile',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customerrepository',
            name='NumOfProducts',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customerrepository',
            name='PointEarned',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customerrepository',
            name='RowNumber',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customerrepository',
            name='SatisfactionScore',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customerrepository',
            name='Surname',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customerrepository',
            name='Tenure',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
