# Generated by Django 3.2.13 on 2023-12-31 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0005_auto_20231231_1754'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frequest_query_set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=2000)),
                ('query', models.CharField(max_length=2000)),
            ],
        ),
    ]
