# Generated by Django 3.2.13 on 2024-01-01 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0006_frequest_query_set'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchedEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('searched_value', models.CharField(max_length=255)),
                ('searched_by', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.customerrepository')),
            ],
        ),
    ]
