# Generated by Django 3.2.13 on 2024-01-06 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0007_searchedentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='complaints_info',
            fields=[
                ('auto_id', models.AutoField(primary_key=True, serialize=False)),
                ('complain_id', models.CharField(editable=False, max_length=12)),
                ('urgency', models.CharField(max_length=100)),
                ('customer_id', models.CharField(max_length=100)),
                ('complained_through', models.CharField(max_length=100)),
                ('mobile_no', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('remarks', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='complain_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
                ('query', models.CharField(max_length=100)),
                ('other_query', models.TextField(blank=True)),
                ('complain_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.complaints_info')),
            ],
        ),
    ]
