# Generated by Django 3.2.13 on 2024-01-06 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0008_complain_details_complaints_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain_details',
            name='other_query',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='complaints_info',
            name='remarks',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
