# Generated by Django 3.2.13 on 2024-01-07 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0009_auto_20240106_2104'),
    ]

    operations = [
        migrations.DeleteModel(
            name='complain_details',
        ),
        migrations.DeleteModel(
            name='complaints_info',
        ),
    ]
